# 예외 처리
자바 컴파일러는 소스 파일을 컴파일할 때 일반 예외가 발생할 가능성이 있는 코드를 발견하면 컴파일 에러를 발생시켜 개발자가 강제적으로 **예외 처리 코드**를 작성하도록 요구한다. 그러나 실행 예외는 컴파일러가 체크해주지 않기 때문에 개발자의 경험을 바탕으로 예외 처리 코드를 작성해야 한다.

## 예외 처리 코드
**try-catch-finally 블록**은 생성자 내부와 메소드 내부에서 작성되어 일반 예외와 실행 예외가 발생할 경우 예외 처리를 할 수 있도록 해 준다. try-catch-finally 블록은 아래와 같이 작성한다.

> try {
>
> 예외 발생 가능 코드
>
> } catch(예외클래스 e) {
>
> 예외 처리
>
> } finally {
>
> 항상 실행;
>
> }

Class.forName() 메소드는 매개값으로 주어진 클래스가 존재하면 Class 객체를 리턴하지만, 존재하지 않으면 ClassNotFoundException을 발생시킨다.

ClassNotFoundException은 일반 예외이므로 컴파일러는 개발자에게 TryCatchFinallyEx.java 파일과 같이 예외 처리 코드를 작성하도록 요구한다.

해당 파일을 실행하면 java.lang.String2 클래스가 존재하지 않았기 때문에 예외 처리가 되었다.

ArrayIndexOutOFBoundsException이나 NumberFormatException과 같은 실행 예외는 컴파일러가 예외 처리 코드를 체크하지 않는다. 오로지 개발자의 경험에 의해 예외 처리를 TryCatchFinallyRuntimeExceptionEx.java 파일과 같이 작성해주어야 한다.

해당 파일을 실행시키면 ArrayIndexOutOfBoundsException이 발생하는데, 이는 실행 매개값을 주지 않았기 때문이다.

## 예외 종류에 따른 처리 코드
### 다중 catch
try 블록 내부는 다양한 예외가 발생할 수 있다. 이 경우 발생되는 예외별로 예외 처리 코드를 다르게 하기 위해 **다중 catch 블록**을 작성한다. catch 블록의 예외 클래스 타입은 try 블록에서 발생된 예외의 종류를 말하는데, try 블록에서 해당 타입의 예외가 발생하면 catch 블록을 실행하도록 되어 있다.

catch 블록이 여러 개라 할지라도 단 하나의 catch 블록만 실행된다. 그 이유는 try 블록에서 동시 다발적으로 예외가 발생하지 않고, 하나의 예외가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문이다.

해당 부분에 대한 손코딩은 CatchByExceptionKindEx.java 파일을 참고하면 된다.

### catch 순서
다중 catch 블록을 작성할 때 주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다는 것이다. try 블록에서 예외가 발생했을 때, 예외를 처리해줄 catch 블록은 위에서부터 차례대로 검색된다. 만약 상위 예외 클래스의 catch 블록이 위에 있다면, 하위 예외 클래스의 catch 블록은 실행되지 않는다. 왜냐하면 하위 예외는 상위 예외를 상속했기 때문에 상위 예외 타입도 되기 때문이다.

따라서 아래 코드는 잘못 코딩되었다.

> try {
>
> ArrayIndexOutOfBoundsException 발생
>
> NumberFormatException 발생
>
> } catch(Exception e) {
>
> 예외 처리1
>
> } catch(ArrayIndexOutOfBoundsException e) {
>
> 예외 처리2
>
> }

ArrayIndexOutOfBoundsException과 NumberFormatException은 모두 Exception을 상속받기 때문에 첫 번째 catch 블록만 선택되어 실행된다. 두 번째 catch 블록은 어떤 경우에라도 실행되지 않는다. 따라서 위 코드는 아래와 같이 수정되어야 한다.

> try {
>
> ArrayIndexOutOfBoundsException 발생
>
> 다른 Exception 발생
>
> } catch(ArrayIndexOutOfBoundsException e) {
>
> 예외 처리 1
>
> } catch(Exception e) {
>
> 예외 처리 2
>
> }

try 블록에서 ArrayIndexOutOfBoundsException이 발생하면 첫 번째 catch 블록을 실행하고, 그 밖의 다른 예외가 발생하면 두 번째 catch 블록을 실행한다.

해당 부분에 대한 손코딩은 CatchOrderEx.java 파일을 참고하면 된다.

## 예외 떠넘기기
메소드 내부에서 예외가 발생할 수 있는 코드를 작성할 때 try-catch 블록으로 예외를 처리하는 것이 기본이지만, 경우에 따라서는 메소드를 호출한 곳으로 예외를 떠넘길 수도 있다. 이 때 사용하는 키워드가 throws이다. **throws 키워드**는 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할을 한다. throws 키워드 뒤에는 떠넘길 예외 클래스를 쉼표로 구분해서 나열해주면 된다.

> 리턴타입 메소드이름(매개변수, ...) throws 예외클래스1, 예외클래스2, ... {
>
> }

발생할 수 있는 예외의 종류별로 throws 뒤에 나열하는 것이 일반적이지만, 아래와 같이 throws Exception만으로 모든 예외를 간단히 떠넘길 수도 있다.

> 리턴타입 메소드이름(매개변수, ...) throws Exception {
>
> }

throws 키워드가 붙어 있는 메소드는 반드시 try 블록 내에서 호출되어야 한다. 그리고 catch 블록에서 떠넘겨 받은 예외를 처리해야 한다. 아래 코드는 throws 키워드가 있는 method2()를 method1()에서 호출하는 방법을 보여준다.

> public void method1() {
>
> try {
>
> method2();
>
> } catch(ClassNotFoundException e) {
>
> //예외 처리 코드
>
> System.out.println("클래스가 존재하지 않습니다.");
>
> }
>
> }
>
> public void method2() throws ClassNotFoundException {
>
> Class clazz = Class.forName("java.lang.String2");
>
> }

method1()에서도 try-catch 블록으로 예외를 처리하지 않고 위와 같이 throws 키워드로 다시 예외를 떠넘길 수 있다. 그러면 method1()을 호출하는 곳에서 try-catch 블록을 사용해서 예외를 처리해야 한다.

> public void method1() throws ClassNotFoundException {
>
> method2();
>
> }

자바 API 도큐먼트를 보면 클래스 생성자와 메소드 선언부에 throws 키워드가 붙어 있는 것을 흔히 볼 수 있다. 이러한 생성자와 메소드를 사용하고 싶다면, 반드시 try-catch 블록으로 예외 처리를 해야 한다. 아니면 throws를 다시 사용해서 예외를 호출한 곳으로 떠넘겨야 한다. 그렇지 않으면 컴파일 에러가 발생한다.

해당 부분에 대한 손코딩은 ThrowsEx.java 파일을 참고하면 된다.

main() 메소드에서도 throws 키워드를 사용해서 예외를 떠넘길 수 있는데, 결국 JVM이 최종적으로 예외 처리를 하게 된다. JVM은 예외의 내용은 콘솔에 출력하는 것으로 예외 처리를 한다.

> publi static void main(String[] args) throws ClassNotFoundException {
>
> findClass();
>
> }

## 핵심 포인트
**예외 처리** : 프로그램에서 예외가 발생했을 경우 프로그램의 갑작스러운 종료를 막고, 정상 실행을 유지할 수 있도록 처리하는 것.

**try-catch=finally 블록** : 생성자 내부와 메소드 내부에서 작성되어 일반 예외와 실행 예외가 발생할 경우 예외 처리를 할 수 있도록 함.

**다중 catch 블록** : catch 블록이 여러 개라 할지라도 단 하나의 catch 블록만 실행된다. 그 이유는 try 블록에서 동시다발적으로 예외가 발생하지 않고, 하나의 예외가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문이다.

**throws 키워드** : 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할. throws 키워드 뒤에는 떠넘길 예외 클래스를 쉼표로 구분해서 나열함.
